/**
 * Bleumi Pay REST API
 * A simple and powerful REST API to integrate Algorand, Ethereum, ERC-20, xDai payments and/or payouts into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { AlgorandWalletAddress } from './algorandWalletAddress';

export class AlgorandAddress {
    'algMainnet'?: { [key: string]: AlgorandWalletAddress; };
    'algTestnet'?: { [key: string]: AlgorandWalletAddress; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "algMainnet",
            "baseName": "alg_mainnet",
            "type": "{ [key: string]: AlgorandWalletAddress; }"
        },
        {
            "name": "algTestnet",
            "baseName": "alg_testnet",
            "type": "{ [key: string]: AlgorandWalletAddress; }"
        }    ];

    static getAttributeTypeMap() {
        return AlgorandAddress.attributeTypeMap;
    }
}

