/**
 * Bleumi Pay API
 * A simple and powerful REST API to integrate Algorand, Ethereum, ERC-20 and xDai payments and/or payouts into your business
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { AlgorandWalletInputs } from './algorandWalletInputs';

export class AlgorandWalletAddress {
    /**
    * Wallet address for the payment in the network
    */
    'addr': string;
    'inputs'?: AlgorandWalletInputs;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addr",
            "baseName": "addr",
            "type": "string"
        },
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "AlgorandWalletInputs"
        }    ];

    static getAttributeTypeMap() {
        return AlgorandWalletAddress.attributeTypeMap;
    }
}

