/**
 * Bleumi Pay REST API
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai, Algorand payments and/or payouts into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* Network enumeration. Please refer to the Supported Networks.
*/
export enum Chain {
    Mainnet = <any> 'mainnet',
    Goerli = <any> 'goerli',
    Xdai = <any> 'xdai',
    XdaiTestnet = <any> 'xdai_testnet',
    AlgMainnet = <any> 'alg_mainnet',
    AlgTestnet = <any> 'alg_testnet',
    Rsk = <any> 'rsk',
    RskTestnet = <any> 'rsk_testnet'
}
