/**
 * Bleumi Pay API
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai payments and/or payouts into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class CheckoutToken {
    /**
    * The chain in which the token is defined
    */
    'chain': string;
    /**
    * The destination address when payments are received in this token
    */
    'transferAddress': string;
    /**
    * Name of the token
    */
    'name': string;
    /**
    * Symbol of the token
    */
    'symbol': string;
    /**
    * Token decimal places
    */
    'decimals': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "chain",
            "baseName": "chain",
            "type": "string"
        },
        {
            "name": "transferAddress",
            "baseName": "transferAddress",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string"
        },
        {
            "name": "decimals",
            "baseName": "decimals",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CheckoutToken.attributeTypeMap;
    }
}

