/**
 * Bleumi Pay REST API
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai, Algorand payments and/or payouts into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class CreatePaymentRequest {
    /**
    * Unique ID identifying the payment
    */
    'id': string;
    /**
    * (Only for Algorand Standard Asset) Asset id which will be used for payment.
    */
    'token'?: string;
    /**
    * Address of buyer. Refund operations on this payment will use this address. You can set this to your address to manually handle refunds (outside of Bleumi Pay) to your buyer. This address must be able to receive payments from smart contracts.
    */
    'buyerAddress': string;
    /**
    * Your deposit address. Settle operations on this payment will use this address. This address must be able to receive payments from smart contracts.
    */
    'transferAddress': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        },
        {
            "name": "buyerAddress",
            "baseName": "buyerAddress",
            "type": "string"
        },
        {
            "name": "transferAddress",
            "baseName": "transferAddress",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreatePaymentRequest.attributeTypeMap;
    }
}

