/**
 * Bleumi Pay API
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai payments and/or payouts into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Chain } from './chain';
import { EthAddress } from './ethAddress';
import { Token } from './token';

export class CreateCheckoutUrlRequest {
    /**
    * Unique identifier for this payment.
    */
    'id': string;
    /**
    * Currency Code
    */
    'currency': string;
    /**
    * Set the token which must be used by the buyer for this payment.
    */
    'amount': string;
    /**
    * Buyer will be redirected to this URL upon canceling the payment.
    */
    'cancelUrl': string;
    /**
    * Buyer will be redirected to this URL upon successfully completing the payment.
    */
    'successUrl': string;
    'buyerAddress'?: EthAddress;
    'chain'?: Chain;
    'token'?: Token;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "cancelUrl",
            "baseName": "cancelUrl",
            "type": "string"
        },
        {
            "name": "successUrl",
            "baseName": "successUrl",
            "type": "string"
        },
        {
            "name": "buyerAddress",
            "baseName": "buyerAddress",
            "type": "EthAddress"
        },
        {
            "name": "chain",
            "baseName": "chain",
            "type": "Chain"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "Token"
        }    ];

    static getAttributeTypeMap() {
        return CreateCheckoutUrlRequest.attributeTypeMap;
    }
}

