import { BadRequest } from "./badRequest";

/**
 * Bleumi Pay API
 * A simple and powerful REST API to integrate ERC20 payments into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class EthAddress {
    /**
    * Valid Ethereum address string should pass validation pattern /^0x[a-fA-F0-9]{40}$/
    */
    //'addr': string;

    private _addr: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addr",
            "baseName": "addr",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EthAddress.attributeTypeMap;
    }

    get addr(): string {
        return this._addr;
    }

    set addr(value: string){
        var regex = /^0x[a-fA-F0-9]{40}$/
        if (regex.test(value)) {
            this._addr = value;
        } else {
            console.warn("Not a valid Ethereum address", value, this);
            var badRequest = new BadRequest();
            badRequest.errorCode = "400";
            badRequest.errorMessage = "Not a valid Ethereum address" ;
            throw badRequest; 
        }
    }

    constructor(public address: string) {
        var regex = /^0x[a-fA-F0-9]{40}$/
        if (!regex.test(address)) {
            console.warn("Not a valid Ethereum address", address, this);
            var badRequest = new BadRequest();
            badRequest.errorCode = "400";
            badRequest.errorMessage = "Not a valid Ethereum address" ;
            throw badRequest;     
        }
        this._addr = address;
    }
}

