/**
 * Bleumi Pay REST API
 * A simple and powerful REST API to integrate Algorand, Ethereum, ERC-20, xDai payments and/or payouts into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { EthereumWalletAddress } from './ethereumWalletAddress';

export class EthereumAddress {
    'mainnet'?: { [key: string]: EthereumWalletAddress; };
    'goerli'?: { [key: string]: EthereumWalletAddress; };
    'xdai'?: { [key: string]: EthereumWalletAddress; };
    'xdaiTestnet'?: { [key: string]: EthereumWalletAddress; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mainnet",
            "baseName": "mainnet",
            "type": "{ [key: string]: EthereumWalletAddress; }"
        },
        {
            "name": "goerli",
            "baseName": "goerli",
            "type": "{ [key: string]: EthereumWalletAddress; }"
        },
        {
            "name": "xdai",
            "baseName": "xdai",
            "type": "{ [key: string]: EthereumWalletAddress; }"
        },
        {
            "name": "xdaiTestnet",
            "baseName": "xdai_testnet",
            "type": "{ [key: string]: EthereumWalletAddress; }"
        }    ];

    static getAttributeTypeMap() {
        return EthereumAddress.attributeTypeMap;
    }
}

