/**
 * Bleumi Pay API
 * A simple and powerful REST API to integrate ERC20 payments into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum EthNetwork {
    Mainnet = <any> 'mainnet',
    Ropsten = <any> 'ropsten',
    Goerli = <any> 'goerli',
    Kovan = <any> 'kovan',
    Rinkeby = <any> 'rinkeby'
}
