/**
 * Bleumi Pay API
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai payments and/or payouts into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PayoutItem } from './payoutItem';

export class PaginatedPayoutItems {
    /**
    * List of payouts of the payment in the current page
    */
    'results': Array<PayoutItem>;
    /**
    * Cursor to fetch next page of results, empty if no more results
    */
    'nextToken'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<PayoutItem>"
        },
        {
            "name": "nextToken",
            "baseName": "nextToken",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaginatedPayoutItems.attributeTypeMap;
    }
}

