/**
 * Bleumi Pay API
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai payments and/or payouts into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { AlgorandAddress } from './algorandAddress';
import { EthereumAddress } from './ethereumAddress';
import { RskAddress } from './rskAddress';

/**
* Payment addresses
*/
export class PaymentAddresses {
    'ethereum'?: EthereumAddress;
    'algorand'?: AlgorandAddress;
    'rsk'?: RskAddress;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ethereum",
            "baseName": "ethereum",
            "type": "EthereumAddress"
        },
        {
            "name": "algorand",
            "baseName": "algorand",
            "type": "AlgorandAddress"
        },
        {
            "name": "rsk",
            "baseName": "rsk",
            "type": "RskAddress"
        }    ];

    static getAttributeTypeMap() {
        return PaymentAddresses.attributeTypeMap;
    }
}

