/**
 * Bleumi Pay REST API
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai, Algorand payments and/or payouts into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { AlgorandBalance } from './algorandBalance';
import { EthereumBalance } from './ethereumBalance';
import { RskBalance } from './rskBalance';

/**
* Payment Balances
*/
export class PaymentBalances {
    'ethereum'?: EthereumBalance;
    'algorand'?: AlgorandBalance;
    'rsk'?: RskBalance;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ethereum",
            "baseName": "ethereum",
            "type": "EthereumBalance"
        },
        {
            "name": "algorand",
            "baseName": "algorand",
            "type": "AlgorandBalance"
        },
        {
            "name": "rsk",
            "baseName": "rsk",
            "type": "RskBalance"
        }    ];

    static getAttributeTypeMap() {
        return PaymentBalances.attributeTypeMap;
    }
}

