/**
 * Bleumi Pay API
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai payments and/or payouts into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaymentOperationInputs } from './paymentOperationInputs';

/**
* Payment Operation details
*/
export class PaymentOperation {
    /**
    * Transaction ID of the operation
    */
    'txid'?: string;
    /**
    * Network in which the operation was carried out
    */
    'chain': string;
    /**
    * The name of the function invoked on the payment processor
    */
    'funcName': string;
    /**
    * null - Operation in progress ; true - Operation completed successfuly ; false - Operation failed to process
    */
    'status': boolean;
    'inputs': PaymentOperationInputs;
    /**
    * Transaction hash of operation submitted to the network. This field is blank when operation is in progress.
    */
    'hash': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "txid",
            "baseName": "txid",
            "type": "string"
        },
        {
            "name": "chain",
            "baseName": "chain",
            "type": "string"
        },
        {
            "name": "funcName",
            "baseName": "funcName",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "boolean"
        },
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "PaymentOperationInputs"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PaymentOperation.attributeTypeMap;
    }
}

