/**
 * Bleumi Pay API
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai payments and/or payouts into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class PaymentOperationInputs {
    /**
    * Address of the wallet
    */
    'addr': string;
    /**
    * Amount (Only for settle operation)
    */
    'amount': string;
    /**
    * ETH - for Ethereum ; XDAI - for xDai ; XDAIT - for xDai Testnet ; <contract address of ERC-20 token> - for ERC-20 Tokens 
    */
    'token': string;
    /**
    * Token amount to be settled in network format (Only for settle operation)
    */
    'tokenAmount': string;
    /**
    * Token decimal places (Only for settle operation)
    */
    'tokenDecimals': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addr",
            "baseName": "addr",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        },
        {
            "name": "tokenAmount",
            "baseName": "token_amount",
            "type": "string"
        },
        {
            "name": "tokenDecimals",
            "baseName": "token_decimals",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PaymentOperationInputs.attributeTypeMap;
    }
}

