/**
 * Bleumi Pay API
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai payments and/or payouts into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PayoutItemInputs } from './payoutItemInputs';

export class PayoutItem {
    /**
    * Unique identifier for this payout
    */
    'txid': string;
    /**
    * null- Operation in progress ; true - Operation confirmed by network; false - Operation rejected by network;
    */
    'status': boolean;
    /**
    * Transaction hash of the operation submitted to the network. This field is blank when the operation is in progress.
    */
    'hash': string;
    /**
    * UNIX timestamp when the payout was created
    */
    'createdAt': number;
    /**
    * UNIX timestamp when the lastest operation was performed
    */
    'updatedAt': number;
    'inputs': PayoutItemInputs;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "txid",
            "baseName": "txid",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "boolean"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "number"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "number"
        },
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "PayoutItemInputs"
        }    ];

    static getAttributeTypeMap() {
        return PayoutItem.attributeTypeMap;
    }
}

