/**
 * Bleumi Pay API
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai payments and/or payouts into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Payout } from './payout';

export class PayoutItemInputs {
    /**
    * Unique identifier generated for the txid of the payout (specified during Create a Payout).
    */
    'salt': string;
    /**
    * Token used for the payout
    */
    'token': string;
    /**
    * Array of payments to be made in this payout. This is an atomic transaction (i.e. either all payments are processed or all of them are rejected).
    */
    'payouts': Array<Payout>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "salt",
            "baseName": "salt",
            "type": "string"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        },
        {
            "name": "payouts",
            "baseName": "payouts",
            "type": "Array<Payout>"
        }    ];

    static getAttributeTypeMap() {
        return PayoutItemInputs.attributeTypeMap;
    }
}

