/**
 * Bleumi Pay REST API
 * A simple and powerful REST API to integrate Algorand, Ethereum, ERC-20 and xDai payments and/or payouts into your business
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { WalletBalance } from './walletBalance';

export class RskBalance {
    'rsk'?: { [key: string]: WalletBalance; };
    'rskTestnet'?: { [key: string]: WalletBalance; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "rsk",
            "baseName": "rsk",
            "type": "{ [key: string]: WalletBalance; }"
        },
        {
            "name": "rskTestnet",
            "baseName": "rsk_testnet",
            "type": "{ [key: string]: WalletBalance; }"
        }    ];

    static getAttributeTypeMap() {
        return RskBalance.attributeTypeMap;
    }
}

