/**
 * Bleumi Pay API
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai payments and/or payouts into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class ValidateCheckoutRequest {
    /**
    * Payment Details. Passed as GET parameter in successUrl.
    */
    'hmacInput': string;
    /**
    * KeyId used to generate the HMAC. Passed as GET parameter in successUrl.
    */
    'hmacKeyId': string;
    /**
    * Algorithm used to generate the HMAC. Passed as GET parameter in successUrl.
    */
    'hmacAlg': string;
    /**
    * HMAC passed as GET parameter in successUrl.
    */
    'hmacValue': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hmacInput",
            "baseName": "hmac_input",
            "type": "string"
        },
        {
            "name": "hmacKeyId",
            "baseName": "hmac_keyId",
            "type": "string"
        },
        {
            "name": "hmacAlg",
            "baseName": "hmac_alg",
            "type": "string"
        },
        {
            "name": "hmacValue",
            "baseName": "hmac_value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ValidateCheckoutRequest.attributeTypeMap;
    }
}

