/**
 * Bleumi Pay API
 * A simple and powerful REST API to integrate ERC20 payments into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WalletOperationInputs } from './walletOperationInputs';

export class WalletOperation {
    /**
    * Unique ID of the wallet; specified when it was created by your system
    */
    'id'?: string;
    /**
    * The name of the function invoked on the payment processor 
    */
    'funcName': string;
    /**
    * <b>null</b> - operation in progress <br/> <b>true</b> - operation completed successfuly <br/> <b>false</b> - operation failed to process
    */
    'status': boolean;
    'inputs': WalletOperationInputs;
    /**
    * Transaction hash of operation submitted to the network. This field is blank when operation is in progress.
    */
    'hash': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "funcName",
            "baseName": "funcName",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "boolean"
        },
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "WalletOperationInputs"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WalletOperation.attributeTypeMap;
    }
}

