/**
 * Bleumi Pay API
 * A simple and powerful REST API to integrate ERC20 payments into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class WalletOperationInputs {
    /**
    * Amount to be settled
    */
    'amount': string;
    /**
    * Address of the ERC-20 token
    */
    'token': string;
    /**
    * Amount in full precision
    */
    'tokenAmount': string;
    'tokenDecimals': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        },
        {
            "name": "tokenAmount",
            "baseName": "token_amount",
            "type": "string"
        },
        {
            "name": "tokenDecimals",
            "baseName": "token_decimals",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WalletOperationInputs.attributeTypeMap;
    }
}

