/**
 * Bleumi Pay API
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai payments and/or payouts into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class WalletBalance {
    /**
    * Token balance for the wallet
    */
    'balance': string;
    /**
    * Token balance for the wallet in Ethereum format
    */
    'tokenBalance': string;
    /**
    * Token decimal places
    */
    'tokenDecimals': number;
    /**
    * Block in which the balance was last updated
    */
    'blockNum': string;
    /**
    * Safety level indicator
    */
    'safety': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "balance",
            "baseName": "balance",
            "type": "string"
        },
        {
            "name": "tokenBalance",
            "baseName": "token_balance",
            "type": "string"
        },
        {
            "name": "tokenDecimals",
            "baseName": "token_decimals",
            "type": "number"
        },
        {
            "name": "blockNum",
            "baseName": "blockNum",
            "type": "string"
        },
        {
            "name": "safety",
            "baseName": "safety",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WalletBalance.attributeTypeMap;
    }
}

