/**
 * Bleumi Pay API
 * A simple and powerful REST API to integrate ERC20 payments into your business or application
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@bleumi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class WalletBalance {
    /**
    * Address of the buyer
    */
    'balance': string;
    /**
    * Address of the merchant
    */
    'tokenBalance': string;
    /**
    * Wallet Library address
    */
    'tokenDecimals': number;
    /**
    * Wallet Proxy address
    */
    'blockNum': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "balance",
            "baseName": "balance",
            "type": "string"
        },
        {
            "name": "tokenBalance",
            "baseName": "token_balance",
            "type": "string"
        },
        {
            "name": "tokenDecimals",
            "baseName": "token_decimals",
            "type": "number"
        },
        {
            "name": "blockNum",
            "baseName": "blockNum",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return WalletBalance.attributeTypeMap;
    }
}

